services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:18.1
    container_name: gofleet_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gofleet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
      - ./sql/migrations/00001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d gofleet"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: gofleet_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8.4-alpine
    container_name: gofleet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- APP GO ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api
    container_name: gofleet_api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      OTEL_SERVICE_NAME: "gofleet-api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true" # n√£o usar TLS (estamos em dev)
      OTEL_TRACES_SAMPLER: "always_on"
      WEB_SERVER_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  fleet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: fleet
    container_name: gofleet_fleet
    ports:
      - "50051:50051"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OTEL_SERVICE_NAME: "gofleet-fleet"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"
    depends_on:
      redis:
       condition: service_healthy
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: worker
    container_name: gofleet_worker
    environment:
      DB_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      FLEET_HOST: fleet
      FLEET_PORT: 50051
      AMQP_PORT: 5672
      OTEL_SERVICE_NAME: "gofleet-worker"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"
    depends_on:
     postgres:
      condition: service_healthy
     rabbitmq:
      condition: service_healthy
     fleet:
      condition: service_started
    restart: on-failure

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local