global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gofleet-api'
    static_configs:
      - targets: ['gofleet_api:2112']

  - job_name: 'gofleet-fleet'
    static_configs:
      - targets: ['gofleet_fleet:2112']

  - job_name: 'gofleet-worker'
    static_configs:
      - targets: ['gofleet_worker:2112']